apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: {{ .Values.ns }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
  labels:
    app: my-python-app
  namespace: {{ .Values.ns }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      serviceAccountName: my-service-account
      containers:
        - name: my-python-app
          image: andresia/assessment:18
          resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-python-app
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: my-python-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: my-python-app
# spec:
#   entryPoints:
#     - web
#   routes:
#     - match: Host(`your-domain.com`) && PathPrefix(`/`)
#       kind: Rule
#       services:
#         - name: my-python-app
#           port: 8080
