
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qa-role
  namespace: dev
rules:
- apiGroups: [""]
  resources:
  - pods
  - deployments
  - statefulsets
  - services
  - configmaps
  - secrets
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qa-role
  namespace: staging
rules:
- apiGroups: [""]
  resources:
  - pods
  - deployments
  - statefulsets
  - services
  - configmaps
  - secrets
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "describe"]
